import { Download, Lock, Unlock } from 'lucide-react';
import type { ImageFormat } from '@/types/editor';

type Props = { originalWidth: number; originalHeight: number; fileSize: number; cropWidth: number | null; cropHeight: number | null; outputWidth: number | null; outputHeight: number | null; format: ImageFormat; quality: number; width: number | null; height: number | null; lockAspectRatio: boolean; isLoading: boolean; onFormatChange: (format: ImageFormat) => void; onQualityChange: (quality: number) => void; onWidthChange: (value: string) => void; onHeightChange: (value: string) => void; onLockToggle: () => void; onDownload: () => void; };

export function ExportPanel({ originalWidth, originalHeight, fileSize, cropWidth, cropHeight, outputWidth, outputHeight, format, quality, width, height, lockAspectRatio, isLoading, onFormatChange, onQualityChange, onWidthChange, onHeightChange, onLockToggle, onDownload }: Props) {
  return (
    <aside className="export-panel" aria-label="Export controls">
      <div className="panel-heading"><div><div className="panel-label">Export</div><h2>Output</h2></div><span className="local-badge">Local</span></div>
      <section className="export-section-block"><label htmlFor="format-select">Format</label><select id="format-select" value={format} onChange={(event) => onFormatChange(event.target.value as ImageFormat)}><option value="png">PNG</option><option value="jpeg">JPEG</option><option value="webp">WebP</option></select></section>
      <section className="export-section-block"><div className="section-label-row"><label>Dimensions</label><button className={`mini-lock ${lockAspectRatio ? 'active' : ''}`} onClick={onLockToggle} title={lockAspectRatio ? 'Unlock aspect ratio' : 'Maintain aspect ratio'} aria-label={lockAspectRatio ? 'Unlock aspect ratio' : 'Maintain aspect ratio'}>{lockAspectRatio ? <Lock size={13} /> : <Unlock size={13} />}{lockAspectRatio ? 'Locked' : 'Free'}</button></div><div className="dimension-stack"><div><label className="dimension-label" htmlFor="output-width">Width</label><input id="output-width" type="number" value={width ?? ''} onChange={(event) => onWidthChange(event.target.value)} min="1" aria-label="Output width in pixels" /></div><span>×</span><div><label className="dimension-label" htmlFor="output-height">Height</label><input id="output-height" type="number" value={height ?? ''} onChange={(event) => onHeightChange(event.target.value)} min="1" aria-label="Output height in pixels" /></div></div><small>{lockAspectRatio ? 'Changing width or height immediately derives the other dimension.' : 'Width and height can be set independently.'}</small></section>
      <section className="export-section-block"><div className="section-label-row"><label htmlFor="quality-slider">Quality</label><span>{Math.round(quality * 100)}%</span></div><input className="export-range" type="range" id="quality-slider" min="0.1" max="1" step="0.01" value={quality} onChange={(event) => onQualityChange(Number(event.target.value))} disabled={format === 'png'} /><small>{format === 'png' ? 'PNG uses lossless output.' : 'Higher quality keeps more detail and file weight.'}</small></section>
      <section className="export-stats"><div><span>Crop</span><strong>{cropWidth && cropHeight ? `${Math.round(cropWidth)} × ${Math.round(cropHeight)}` : '--'}</strong></div><div><span>Output</span><strong>{outputWidth && outputHeight ? `${outputWidth} × ${outputHeight}` : '--'}</strong></div><div><span>Source</span><strong>{originalWidth} × {originalHeight}</strong></div><div><span>Source size</span><strong>{(fileSize / 1024).toFixed(1)} KB</strong></div></section>
      <div className="export-spacer" />
      <button className="download-btn" onClick={onDownload} disabled={isLoading || !cropWidth || !cropHeight}>{isLoading ? 'Processing…' : <><Download size={17} /> Download image</>}</button>
    </aside>
  );
}
